import Head from "next/head";

import Layout from "@/components/Layout";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>RatherLabs Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <Header />
        </Layout>
      </main>
    </>
  );
}
