import Head from "next/head";
import { Layout } from "antd";
import Navbar from "@/components/Navbar";

export default function Home() {
  const { Content, Footer } = Layout;

  return (
    <>
      <Head>
        <title>Challenge RatherLabs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout className="layout">
          <Navbar />
          <Content style={{ padding: "0 50px" }}>
            <div className="site-layout-content" style={{ background: "#fff" }}>
              Content
            </div>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            Ant Design ©2023 Created by Ant UED
          </Footer>
        </Layout>
      </main>
    </>
  );
}
